import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Terms of Service',
  description: 'Terms and conditions for using First Unicorn Startup valuation platform.',
}

export default function TermsPage() {
  return (
    <main className="min-h-[calc(100vh-3.5rem)] bg-[oklch(0.08_0.008_260)] py-16 px-6">
      <article className="max-w-3xl mx-auto prose-invert">
        <p className="text-[11px] font-semibold text-[oklch(0.78_0.14_80)] uppercase tracking-[0.2em] mb-4">
          Legal
        </p>
        <h1 className="font-heading text-3xl text-[oklch(0.93_0.005_80)] mb-8">
          Terms of Service
        </h1>
        <p className="text-[11px] text-[oklch(0.40_0.01_260)] mb-10">
          Last updated: March 12, 2026
        </p>

        <div className="space-y-8 text-sm text-[oklch(0.55_0.01_260)] leading-relaxed">
          <Section title="1. Acceptance of Terms">
            <p>
              By accessing or using First Unicorn Startup (&ldquo;the Platform&rdquo;), operated by an IBBI-Registered Insolvency Professional &amp; SFA-Licensed Valuer, you agree to be bound by these Terms of Service. If you do not agree, please do not use the Platform.
            </p>
          </Section>

          <Section title="2. Service Description">
            <p>
              The Platform provides automated startup valuation estimates using 10 quantitative methods across 4 approaches (Income, Market, Asset/Cost, VC/Startup), Monte Carlo simulation, and AI-generated narrative analysis. The Platform also offers Deal Check, Cap Table, and ESOP calculator tools.
            </p>
          </Section>

          <Section title="3. Nature of Valuations">
            <p className="p-4 rounded-lg bg-[oklch(0.12_0.008_260)] border border-[oklch(0.20_0.008_260)]">
              <strong className="text-[oklch(0.93_0.005_80)]">Important Disclaimer:</strong> Valuations generated by this Platform are quantitative estimates based on the data you provide and publicly available benchmarks (Damodaran India). They are <strong className="text-[oklch(0.78_0.14_80)]">not</strong> formal valuation opinions, certified appraisals, or legal advice.
            </p>
            <ul className="list-disc pl-5 space-y-1.5 mt-3">
              <li><strong className="text-[oklch(0.75_0.005_80)]">Indicative reports</strong> are directional estimates with no regulatory validity.</li>
              <li><strong className="text-[oklch(0.75_0.005_80)]">Paid reports</strong> (Fundraising, ESOP, Rule 11UA, FEMA, M&amp;A) include deeper analysis but the final regulatory-compliant valuation requires review and sign-off by a registered valuer.</li>
              <li>No valuation output from this Platform should be filed with regulators, used in legal proceedings, or relied upon for tax compliance without independent professional review.</li>
            </ul>
          </Section>

          <Section title="4. User Responsibilities">
            <ul className="list-disc pl-5 space-y-1.5">
              <li>You are responsible for the accuracy of data you enter into the Platform.</li>
              <li>You must not submit false, misleading, or fraudulent information.</li>
              <li>You must not use the Platform for money laundering, securities fraud, or any illegal purpose.</li>
              <li>You must not attempt to reverse-engineer, scrape, or automate access to the Platform.</li>
            </ul>
          </Section>

          <Section title="5. Payments &amp; Refunds">
            <p>
              Premium reports are priced based on valuation purpose. Payments are processed securely by Razorpay. All prices are in Indian Rupees (INR) and inclusive of applicable taxes.
            </p>
            <p>
              Refunds are available within 7 days of purchase if the report has not been accessed. Once a report is viewed, no refund is available. Contact us to request a refund.
            </p>
          </Section>

          <Section title="6. Intellectual Property">
            <p>
              The Platform, including its valuation methodology, UI design, code, and content, is owned by First Unicorn Startup. You may not reproduce, distribute, or create derivative works without written permission.
            </p>
            <p>
              Your valuation reports are yours to use for your internal business purposes. You may share your report link with investors, advisors, or board members.
            </p>
          </Section>

          <Section title="7. Limitation of Liability">
            <p>
              To the maximum extent permitted by Indian law, First Unicorn Startup shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the Platform, including but not limited to:
            </p>
            <ul className="list-disc pl-5 space-y-1.5">
              <li>Investment decisions made based on valuation outputs</li>
              <li>Regulatory non-compliance from using outputs without professional review</li>
              <li>Loss of business, revenue, or anticipated savings</li>
              <li>Errors in valuation arising from incorrect user inputs</li>
            </ul>
            <p>
              Our total liability shall not exceed the amount you paid for the specific report in question.
            </p>
          </Section>

          <Section title="8. Data &amp; Privacy">
            <p>
              Your use of the Platform is also governed by our{' '}
              <a href="/privacy" className="text-[oklch(0.78_0.14_80)] hover:underline">Privacy Policy</a>.
            </p>
          </Section>

          <Section title="9. Governing Law">
            <p>
              These Terms shall be governed by the laws of India. Any disputes shall be subject to the exclusive jurisdiction of courts in New Delhi, India.
            </p>
          </Section>

          <Section title="10. Changes to Terms">
            <p>
              We may update these Terms from time to time. Continued use of the Platform after changes constitutes acceptance of the updated Terms. Material changes will be communicated via the Platform.
            </p>
          </Section>

          <Section title="11. Contact">
            <p>
              For questions about these Terms, contact us at{' '}
              <a href="mailto:legal@firstunicornstartup.com" className="text-[oklch(0.78_0.14_80)] hover:underline">
                legal@firstunicornstartup.com
              </a>
            </p>
          </Section>
        </div>
      </article>
    </main>
  )
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section>
      <h2 className="font-heading text-lg text-[oklch(0.93_0.005_80)] mb-3">{title}</h2>
      <div className="space-y-3">{children}</div>
    </section>
  )
}
